#pragma once

#include <mlibc/sysdep-signatures.hpp>

namespace mlibc {

struct LyrSysdepsTags : LibcPanic,
                        LibcLog,
                        Isatty,
                        Write,
                        TcbSet,
                        AnonAllocate,
                        AnonFree,
                        VmProtect,
                        Seek,
                        Exit,
                        Close,
                        FutexWake,
                        FutexWait,
                        Read,
                        Open,
                        OpenDir,
                        ReadEntries,
                        Stat,
                        Access,
                        Faccessat,
                        Dup,
                        Dup2,
                        Chmod,
                        Fchmod,
                        Fchmodat,
                        Fchownat,
                        Mkdir,
                        Mkdirat,
                        Rmdir,
                        Unlinkat,
                        Ioctl,
                        Tcgetattr,
                        Tcsetattr,
                        Tcsetwinsize,
                        Chroot,
                        Socket,
                        Bind,
                        Connect,
                        Listen,
                        Accept,
                        Sockname,
                        Peername,
                        Shutdown,
                        SetSockopt,
                        GetSockopt,
                        MsgSend,
                        MsgRecv,
                        VmMap,
                        VmUnmap,
                        Execve,
                        ClockGet,
                        Poll,
                        Fork,
                        GetPid,
                        GetUid,
                        GetEuid,
                        GetGid,
                        GetEgid,
                        GetResuid,
                        GetResgid,
                        SetUid,
                        SetEuid,
                        SetGid,
                        SetEgid,
                        GetGroups,
                        GetTid,
                        GetPpid,
                        GetPgid,
                        GetCwd,
                        Chdir,
                        Pselect,
                        Fcntl,
                        Waitpid,
                        Sleep,
                        Pipe,
                        SetPgid,
                        SetSid,
                        Ttyname,
                        Tcgetwinsize,
                        Uname,
                        GetHostname,
                        Sysconf,
                        Kill,
                        Sigprocmask,
                        Sigaction,
                        Renameat,
                        Rename {};

template <typename Tag> using Sysdeps = SysdepOf<LyrSysdepsTags, Tag>;

} // namespace mlibc
